import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  page: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingBottom: 32,
    paddingTop: 12,
    gap: 12,
  },
  scrollContentWide: {
    maxWidth: 960,
    paddingHorizontal: 32,
  },
  scrollContentSmall: {
    paddingHorizontal: 8,
    gap: 10,
  },
  brandContainer: {
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  brandTitle: {
    fontSize: 22,
    lineHeight: 26,
    fontWeight: '800',
  },
  brandSubtitle: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: '500',
  },
  darkModeToggle: {
    height: 34,
    borderRadius: 20,
    paddingHorizontal: 6,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  darkModeToggleActive: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    borderColor: 'rgba(255,215,0,0.4)',
  },
  darkModeLabel: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    paddingRight: 4,
  },
  darkModeLabelActive: {
    color: '#FFD700',
  },
  switchThumb: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
  },
  switchThumbActive: {
    backgroundColor: '#FFD700',
  },
  gameCard: {
    borderRadius: 10,
    borderWidth: 1,
    padding: 12,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  roundHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    paddingBottom: 14,
    gap: 10,
  },
  roundHeaderResponsive: {
    flexWrap: 'wrap',
  },
  roundTitleGroup: {
    flexGrow: 1,
    flexShrink: 1,
  },
  roundCode: {
    fontSize: 26,
    fontWeight: '800',
  },
  progressText: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
  },
  livePill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  livePillText: {
    fontSize: 11,
    fontWeight: '700',
  },
  questionPanel: {
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderWidth: 1,
  },
  questionLabel: {
    fontSize: 11,
    letterSpacing: 0.8,
    marginBottom: 8,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  questionText: {
    fontSize: 19,
    lineHeight: 26,
    fontWeight: '700',
  },
  triesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    paddingHorizontal: 4,
    paddingVertical: 4,
    gap: 8,
  },
  triesText: {
    fontSize: 13,
    fontWeight: '600',
  },
  timerText: {
    fontSize: 20,
    fontWeight: '800',
  },
  optionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
  },
  optionsGridWide: {
    gap: 12,
  },
  optionButton: {
    width: '48%',
    minHeight: 118,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  optionButtonWide: {
    minHeight: 160,
  },
  optionButtonSmall: {
    width: '100%',
    minHeight: 96,
  },
  optionButtonSelected: {
    borderColor: '#FFFFFF',
    borderWidth: 3,
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
  },
  optionButtonDisabled: {
    opacity: 0.72,
  },
  optionLabel: {
    color: '#FFFFFF',
    fontSize: 36,
    fontWeight: '800',
    lineHeight: 40,
  },
  optionText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 4,
    paddingHorizontal: 4,
    lineHeight: 16,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 8,
  },
  actionRowResponsive: {
    flexWrap: 'wrap',
  },
  actionRowPhone: {
    flexDirection: 'column',
  },
  actionRowWide: {
    gap: 12,
  },
  secondaryAction: {
    flex: 1,
    minHeight: 44,
    paddingVertical: 13,
    borderRadius: 10,
    backgroundColor: 'transparent',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryActionText: {
    fontSize: 15,
    fontWeight: '700',
  },
  primaryAction: {
    flex: 1.5,
    minHeight: 44,
    paddingVertical: 13,
    borderRadius: 10,
    backgroundColor: '#FFD700',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullWidthAction: {
    flexGrow: 0,
    flexShrink: 0,
    flexBasis: 'auto',
    width: '100%',
  },
  primaryActionDisabled: {
    opacity: 0.4,
  },
  primaryActionText: {
    color: '#14162E',
    fontSize: 15,
    fontWeight: '800',
  },
  menuHeader: {
    gap: 6,
  },
  menuTitle: {
    fontSize: 22,
    lineHeight: 28,
    fontWeight: '800',
  },
  menuText: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  menuSection: {
    gap: 8,
  },
  menuSectionTitle: {
    fontSize: 14,
    fontWeight: '800',
  },
  selectionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  selectionButton: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 160,
    minHeight: 58,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 9,
    justifyContent: 'center',
  },
  selectionButtonPhone: {
    flexBasis: '100%',
    width: '100%',
  },
  selectionButtonActive: {
    backgroundColor: '#FFD700',
    borderColor: '#FFD700',
  },
  selectionButtonText: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '800',
  },
  selectionButtonMeta: {
    marginTop: 2,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '700',
  },
  difficultyRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  difficultyButton: {
    flex: 1,
    flexBasis: 96,
    minHeight: 58,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 9,
    justifyContent: 'center',
    alignItems: 'center',
  },
  difficultyButtonPhone: {
    flexBasis: '100%',
    width: '100%',
  },
  dropdownButton: {
    minHeight: 58,
    borderRadius: 10,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  dropdownTextGroup: {
    flex: 1,
  },
  dropdownChevron: {
    width: 24,
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '800',
  },
  dropdownMenu: {
    maxHeight: 260,
    borderRadius: 10,
    borderWidth: 1,
    overflow: 'hidden',
  },
  dropdownScroll: {
    maxHeight: 260,
  },
  dropdownItem: {
    minHeight: 54,
    borderBottomWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
    justifyContent: 'center',
  },
  resultPanel: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 18,
    alignItems: 'center',
    gap: 8,
  },
  resultScore: {
    fontSize: 42,
    lineHeight: 48,
    fontWeight: '800',
  },
  feedbackBanner: {
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  feedbackText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  footerInfo: {
    paddingHorizontal: 2,
  },
  footerText: {
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '500',
  },
});
